name: vehicle-monitoring-stack
services:
  vehicle-monitoring-backend:
    image: vehicle-monitoring-backend:local
    container_name: vehicle-monitoring-backend
    build:
      context: ./backend/src
      dockerfile: ./VehicleMonitoring.Api/Dockerfile
    restart: always
    ports:
      - 8080:8080

  vehicle-monitoring-frontend:
    image: vehicle-monitoring-ui:local
    container_name: vehicle-monitoring-ui
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - vehicle-monitoring-backend
    ports:
      - 4200:80
